"""
API Package
============

Database models and utilities for feature management.
"""

from api.database import Feature, create_database, get_database_path
from api.dependency_resolver import (
    DependencyIssue,
    DependencyResult,
    ValidationResult,
    validate_dependency_graph,
    validate_dependencies,
    resolve_dependencies,
    would_create_circular_dependency,
    are_dependencies_satisfied,
    get_blocking_dependencies,
    get_ready_features,
    get_blocked_features,
    build_graph_data,
    compute_scheduling_scores,
)
from api.prompt_builder import (
    build_system_prompt,
    extract_tool_hints,
    format_tool_hints_as_markdown,
    inject_tool_hints_into_prompt,
)
from api.harness_kernel import (
    BudgetExceeded,
    BudgetTracker,
    ExecutionResult,
    HarnessKernel,
    MaxTurnsExceeded,
)
from api.static_spec_adapter import (
    StaticSpecAdapter,
    get_static_spec_adapter,
    reset_static_spec_adapter,
    INITIALIZER_TOOLS,
    CODING_TOOLS,
    TESTING_TOOLS,
    DEFAULT_BUDGETS,
)
from api.tool_policy import (
    CompiledPattern,
    PatternCompilationError,
    ToolCallBlocked,
    ToolPolicyEnforcer,
    ToolPolicyError,
    check_arguments_against_patterns,
    compile_forbidden_patterns,
    create_enforcer_for_run,
    extract_forbidden_patterns,
    record_blocked_tool_call_event,
    serialize_tool_arguments,
    # Feature #57: Tool Policy Derivation from Task Type
    derive_tool_policy,
    get_tool_set,
    get_standard_forbidden_patterns,
    get_task_forbidden_patterns,
    get_combined_forbidden_patterns,
    get_tool_hints,
    get_supported_task_types,
    TOOL_SETS,
    STANDARD_FORBIDDEN_PATTERNS,
    TASK_SPECIFIC_FORBIDDEN_PATTERNS,
    TASK_TOOL_HINTS,
    # Feature #58: Budget Derivation from Task Complexity
    BASE_BUDGETS,
    MIN_BUDGET,
    MAX_BUDGET,
    DESCRIPTION_LENGTH_THRESHOLDS,
    STEPS_COUNT_THRESHOLDS,
    BudgetResult,
    derive_budget,
    derive_budget_detailed,
    get_base_budget,
    get_budget_bounds,
    get_all_base_budgets,
    # Feature #40: ToolPolicy Allowed Tools Filtering
    ToolDefinition,
    ToolFilterResult,
    extract_allowed_tools,
    filter_tools,
    filter_tools_for_spec,
    get_filtered_tool_names,
    validate_tool_names,
    # Feature #44: Policy Violation Event Logging
    PolicyViolation,
    ViolationAggregation,
    VIOLATION_TYPES,
    create_allowed_tools_violation,
    create_directory_sandbox_violation,
    create_forbidden_patterns_violation,
    get_violation_aggregation,
    record_allowed_tools_violation,
    record_and_aggregate_violation,
    record_directory_sandbox_violation,
    record_forbidden_patterns_violation,
    record_policy_violation_event,
    update_run_violation_metadata,
)
from api.display_derivation import (
    derive_display_name,
    derive_display_properties,
    derive_icon,
    derive_mascot_name,
    extract_first_sentence,
    get_mascot_pool,
    get_task_type_icons,
    truncate_with_ellipsis,
    DISPLAY_NAME_MAX_LENGTH,
    MASCOT_POOL,
    TASK_TYPE_ICONS,
    DEFAULT_ICON,
)
from api.validators import (
    AcceptanceGate,
    FileExistsValidator,
    GateResult,
    Validator,
    ValidatorResult,
    VALIDATOR_REGISTRY,
    evaluate_acceptance_spec,
    evaluate_validator,
    get_validator,
)
from api.feature_compiler import (
    CATEGORY_TO_TASK_TYPE,
    FeatureCompiler,
    compile_feature,
    extract_task_type_from_category,
    get_budget_for_task_type,
    get_feature_compiler,
    get_tools_for_task_type,
    reset_feature_compiler,
    slugify,
)
from api.websocket_events import (
    AcceptanceUpdatePayload,
    ValidatorResultPayload,
    broadcast_acceptance_update,
    broadcast_acceptance_update_sync,
    build_acceptance_update_from_results,
    create_validator_result_payload,
)
from api.event_recorder import (
    EventRecorder,
    get_event_recorder,
    clear_recorder_cache,
)
from api.dspy_signatures import (
    SpecGenerationSignature,
    get_spec_generator,
    validate_spec_output,
    VALID_TASK_TYPES,
    DEFAULT_BUDGETS as DSPY_DEFAULT_BUDGETS,
)

__all__ = [
    "Feature",
    "create_database",
    "get_database_path",
    # Dependency resolver exports
    "DependencyIssue",
    "DependencyResult",
    "ValidationResult",
    "validate_dependency_graph",
    "validate_dependencies",
    "resolve_dependencies",
    "would_create_circular_dependency",
    "are_dependencies_satisfied",
    "get_blocking_dependencies",
    "get_ready_features",
    "get_blocked_features",
    "build_graph_data",
    "compute_scheduling_scores",
    # Prompt builder exports
    "build_system_prompt",
    "extract_tool_hints",
    "format_tool_hints_as_markdown",
    "inject_tool_hints_into_prompt",
    # Harness kernel exports
    "BudgetExceeded",
    "BudgetTracker",
    "ExecutionResult",
    "HarnessKernel",
    "MaxTurnsExceeded",
    # Static spec adapter exports
    "StaticSpecAdapter",
    "get_static_spec_adapter",
    "reset_static_spec_adapter",
    "INITIALIZER_TOOLS",
    "CODING_TOOLS",
    "TESTING_TOOLS",
    "DEFAULT_BUDGETS",
    # Tool policy exports
    "CompiledPattern",
    "PatternCompilationError",
    "ToolCallBlocked",
    "ToolPolicyEnforcer",
    "ToolPolicyError",
    "check_arguments_against_patterns",
    "compile_forbidden_patterns",
    "create_enforcer_for_run",
    "extract_forbidden_patterns",
    "record_blocked_tool_call_event",
    "serialize_tool_arguments",
    # Feature #57: Tool Policy Derivation exports
    "derive_tool_policy",
    "get_tool_set",
    "get_standard_forbidden_patterns",
    "get_task_forbidden_patterns",
    "get_combined_forbidden_patterns",
    "get_tool_hints",
    "get_supported_task_types",
    "TOOL_SETS",
    "STANDARD_FORBIDDEN_PATTERNS",
    "TASK_SPECIFIC_FORBIDDEN_PATTERNS",
    "TASK_TOOL_HINTS",
    # Feature #58: Budget Derivation from Task Complexity exports
    "BASE_BUDGETS",
    "MIN_BUDGET",
    "MAX_BUDGET",
    "DESCRIPTION_LENGTH_THRESHOLDS",
    "STEPS_COUNT_THRESHOLDS",
    "BudgetResult",
    "derive_budget",
    "derive_budget_detailed",
    "get_base_budget",
    "get_budget_bounds",
    "get_all_base_budgets",
    # Feature #40: ToolPolicy Allowed Tools Filtering exports
    "ToolDefinition",
    "ToolFilterResult",
    "extract_allowed_tools",
    "filter_tools",
    "filter_tools_for_spec",
    "get_filtered_tool_names",
    "validate_tool_names",
    # Feature #44: Policy Violation Event Logging exports
    "PolicyViolation",
    "ViolationAggregation",
    "VIOLATION_TYPES",
    "create_allowed_tools_violation",
    "create_directory_sandbox_violation",
    "create_forbidden_patterns_violation",
    "get_violation_aggregation",
    "record_allowed_tools_violation",
    "record_and_aggregate_violation",
    "record_directory_sandbox_violation",
    "record_forbidden_patterns_violation",
    "record_policy_violation_event",
    "update_run_violation_metadata",
    # Display derivation exports
    "derive_display_name",
    "derive_display_properties",
    "derive_icon",
    "derive_mascot_name",
    "extract_first_sentence",
    "get_mascot_pool",
    "get_task_type_icons",
    "truncate_with_ellipsis",
    "DISPLAY_NAME_MAX_LENGTH",
    "MASCOT_POOL",
    "TASK_TYPE_ICONS",
    "DEFAULT_ICON",
    # Validators exports (Feature #35: AcceptanceGate)
    "AcceptanceGate",
    "FileExistsValidator",
    "GateResult",
    "Validator",
    "ValidatorResult",
    "VALIDATOR_REGISTRY",
    "evaluate_acceptance_spec",
    "evaluate_validator",
    "get_validator",
    # Feature compiler exports
    "CATEGORY_TO_TASK_TYPE",
    "FeatureCompiler",
    "compile_feature",
    "extract_task_type_from_category",
    "get_budget_for_task_type",
    "get_feature_compiler",
    "get_tools_for_task_type",
    "reset_feature_compiler",
    "slugify",
    # WebSocket event broadcasting exports (Feature #63)
    "AcceptanceUpdatePayload",
    "ValidatorResultPayload",
    "broadcast_acceptance_update",
    "broadcast_acceptance_update_sync",
    "build_acceptance_update_from_results",
    "create_validator_result_payload",
    # Event recorder exports (Feature #30)
    "EventRecorder",
    "get_event_recorder",
    "clear_recorder_cache",
    # DSPy signature exports (Feature #50)
    "SpecGenerationSignature",
    "get_spec_generator",
    "validate_spec_output",
    "VALID_TASK_TYPES",
    "DSPY_DEFAULT_BUDGETS",
]
